<script setup lang='ts'>
const props = defineProps({
    aigc: {
        type: Boolean,
        default: false
    },
    reprint: {
        type: Boolean,
        default: false
    },
    from: {
        type: String,
        default: 'Unknown'
    },
    author: {
        type: String,
        default: 'Unknown'
    },
    src: {
        type: String,
        required: true
    },
    license: {
        type: String,
        default: null
    },
});
</script>

<template>
    <div class="hint-container info">
        <p class="hint-container-title">Declarations of works</p>
        <ul>
            <li v-if="props.aigc">
                <p><strong>AIGC</strong></p>
                <p>Parts of this article (images/text/code) are generated by artificial intelligence (AI) technology. AI is only used to assist in the expression.</p>
            </li>
            <li v-if="props.reprint">
                <p><strong>Reprinted / Excerpted Content</strong></p>
                <p>Some or all of the content in this article is from {{ from }}<span v-if="props.license">, published under a {{ license }} license</span>. The original article was written by {{ author }} and is subject to deletions/changes.</p>
            </li>
        </ul>
    </div>
</template>

<style scoped lang='scss'>
li {
    p {
        line-height: 1 !important;
        margin: 0.5rem 0;
    }
}
</style>
