<script setup lang='ts'>
const props = defineProps({
    aigc: {
        type: String,
        default: null
    },
    incomp: {
        type: String,
        default: null
    },
    trans: {
        type: String,
        default: null
    },
    reprint: {
        type: String,
        default: null
    },
    from: {
        type: String,
        default: 'Unknown'
    },
    author: {
        type: String,
        default: 'Unknown'
    },
    src: {
        type: String,
        required: true
    },
    license: {
        type: String,
        default: null
    },
});
</script>

<template>
    <div class="hint-container info">
        <p class="hint-container-title">Declaration of works</p>
        <ul>
            <li v-if="props.aigc">
                <p><strong>AIGC</strong></p>
                <p>Parts of this article (images/text/code) are generated by artificial intelligence (AI) technology. AI is only used to assist in the expression.</p>
            </li>
            <li v-if="props.reprint">
                <p><strong>Reprinted / Excerpted Content</strong></p>
                <p>Some or all of the content in this article is from {{ from }}<span v-if="props.license">, published under a {{ license }} license</span>. The original article was written by {{ author }} and is subject to deletions/changes.</p>
            </li>
            <li v-if="props.incomp">
                <p><strong>Incomplete works</strong></p>
                <p>This page is under construction. Please sit and relax. <span v-if="props.trans">However, an article written in another language is already available. You can switch languages if necessary.</span></p>
            </li>
        </ul>
    </div>
</template>

<style scoped lang='scss'>
li {
    p {
        line-height: 1 !important;
        margin: 0.5rem 0;
    }
}
</style>
